import type { RegionEntry } from '@/constants/regionData/types';

/** ISO 3166-2 style subdivisions for countries with financially relevant regional rules. */
export const SUBDIVISIONS: Record<string, RegionEntry[]> = {
  CA: [
    { code: 'AB', name: 'Alberta' },
    { code: 'BC', name: 'Colombie-Britannique' },
    { code: 'MB', name: 'Manitoba' },
    { code: 'NB', name: 'Nouveau-Brunswick' },
    { code: 'NL', name: 'Terre-Neuve-et-Labrador' },
    { code: 'NS', name: 'Nouvelle-Écosse' },
    { code: 'NT', name: 'Territoires du Nord-Ouest' },
    { code: 'NU', name: 'Nunavut' },
    { code: 'ON', name: 'Ontario' },
    { code: 'PE', name: 'Île-du-Prince-Édouard' },
    { code: 'QC', name: 'Québec' },
    { code: 'SK', name: 'Saskatchewan' },
    { code: 'YT', name: 'Yukon' },
  ],
  US: [
    { code: 'AL', name: 'Alabama' },
    { code: 'AK', name: 'Alaska' },
    { code: 'AZ', name: 'Arizona' },
    { code: 'AR', name: 'Arkansas' },
    { code: 'CA', name: 'Californie' },
    { code: 'CO', name: 'Colorado' },
    { code: 'CT', name: 'Connecticut' },
    { code: 'DE', name: 'Delaware' },
    { code: 'DC', name: 'District de Columbia' },
    { code: 'FL', name: 'Floride' },
    { code: 'GA', name: 'Géorgie' },
    { code: 'HI', name: 'Hawaï' },
    { code: 'ID', name: 'Idaho' },
    { code: 'IL', name: 'Illinois' },
    { code: 'IN', name: 'Indiana' },
    { code: 'IA', name: 'Iowa' },
    { code: 'KS', name: 'Kansas' },
    { code: 'KY', name: 'Kentucky' },
    { code: 'LA', name: 'Louisiane' },
    { code: 'ME', name: 'Maine' },
    { code: 'MD', name: 'Maryland' },
    { code: 'MA', name: 'Massachusetts' },
    { code: 'MI', name: 'Michigan' },
    { code: 'MN', name: 'Minnesota' },
    { code: 'MS', name: 'Mississippi' },
    { code: 'MO', name: 'Missouri' },
    { code: 'MT', name: 'Montana' },
    { code: 'NE', name: 'Nebraska' },
    { code: 'NV', name: 'Nevada' },
    { code: 'NH', name: 'New Hampshire' },
    { code: 'NJ', name: 'New Jersey' },
    { code: 'NM', name: 'Nouveau-Mexique' },
    { code: 'NY', name: 'New York' },
    { code: 'NC', name: 'Caroline du Nord' },
    { code: 'ND', name: 'Dakota du Nord' },
    { code: 'OH', name: 'Ohio' },
    { code: 'OK', name: 'Oklahoma' },
    { code: 'OR', name: 'Oregon' },
    { code: 'PA', name: 'Pennsylvanie' },
    { code: 'RI', name: 'Rhode Island' },
    { code: 'SC', name: 'Caroline du Sud' },
    { code: 'SD', name: 'Dakota du Sud' },
    { code: 'TN', name: 'Tennessee' },
    { code: 'TX', name: 'Texas' },
    { code: 'UT', name: 'Utah' },
    { code: 'VT', name: 'Vermont' },
    { code: 'VA', name: 'Virginie' },
    { code: 'WA', name: 'Washington' },
    { code: 'WV', name: 'Virginie-Occidentale' },
    { code: 'WI', name: 'Wisconsin' },
    { code: 'WY', name: 'Wyoming' },
  ],
  CH: [
    { code: 'AG', name: 'Argovie' },
    { code: 'AI', name: 'Appenzell Rhodes-Intérieures' },
    { code: 'AR', name: 'Appenzell Rhodes-Extérieures' },
    { code: 'BE', name: 'Berne' },
    { code: 'BL', name: 'Bâle-Campagne' },
    { code: 'BS', name: 'Bâle-Ville' },
    { code: 'FR', name: 'Fribourg' },
    { code: 'GE', name: 'Genève' },
    { code: 'GL', name: 'Glaris' },
    { code: 'GR', name: 'Grisons' },
    { code: 'JU', name: 'Jura' },
    { code: 'LU', name: 'Lucerne' },
    { code: 'NE', name: 'Neuchâtel' },
    { code: 'NW', name: 'Nidwald' },
    { code: 'OW', name: 'Obwald' },
    { code: 'SG', name: 'Saint-Gall' },
    { code: 'SH', name: 'Schaffhouse' },
    { code: 'SO', name: 'Soleure' },
    { code: 'SZ', name: 'Schwytz' },
    { code: 'TG', name: 'Thurgovie' },
    { code: 'TI', name: 'Tessin' },
    { code: 'UR', name: 'Uri' },
    { code: 'VD', name: 'Vaud' },
    { code: 'VS', name: 'Valais' },
    { code: 'ZG', name: 'Zoug' },
    { code: 'ZH', name: 'Zurich' },
  ],
  AU: [
    { code: 'ACT', name: 'Territoire de la capitale australienne' },
    { code: 'NSW', name: 'Nouvelle-Galles du Sud' },
    { code: 'NT', name: 'Territoire du Nord' },
    { code: 'QLD', name: 'Queensland' },
    { code: 'SA', name: 'Australie-Méridionale' },
    { code: 'TAS', name: 'Tasmanie' },
    { code: 'VIC', name: 'Victoria' },
    { code: 'WA', name: 'Australie-Occidentale' },
  ],
  MX: [
    { code: 'AGU', name: 'Aguascalientes' },
    { code: 'BCN', name: 'Basse-Californie' },
    { code: 'BCS', name: 'Basse-Californie du Sud' },
    { code: 'CAM', name: 'Campeche' },
    { code: 'CHP', name: 'Chiapas' },
    { code: 'CHH', name: 'Chihuahua' },
    { code: 'COA', name: 'Coahuila' },
    { code: 'COL', name: 'Colima' },
    { code: 'CMX', name: 'Mexico' },
    { code: 'DUR', name: 'Durango' },
    { code: 'GUA', name: 'Guanajuato' },
    { code: 'GRO', name: 'Guerrero' },
    { code: 'HID', name: 'Hidalgo' },
    { code: 'JAL', name: 'Jalisco' },
    { code: 'MEX', name: 'État de Mexico' },
    { code: 'MIC', name: 'Michoacán' },
    { code: 'MOR', name: 'Morelos' },
    { code: 'NAY', name: 'Nayarit' },
    { code: 'NLE', name: 'Nuevo León' },
    { code: 'OAX', name: 'Oaxaca' },
    { code: 'PUE', name: 'Puebla' },
    { code: 'QUE', name: 'Querétaro' },
    { code: 'ROO', name: 'Quintana Roo' },
    { code: 'SLP', name: 'San Luis Potosí' },
    { code: 'SIN', name: 'Sinaloa' },
    { code: 'SON', name: 'Sonora' },
    { code: 'TAB', name: 'Tabasco' },
    { code: 'TAM', name: 'Tamaulipas' },
    { code: 'TLA', name: 'Tlaxcala' },
    { code: 'VER', name: 'Veracruz' },
    { code: 'YUC', name: 'Yucatán' },
    { code: 'ZAC', name: 'Zacatecas' },
  ],
  BR: [
    { code: 'AC', name: 'Acre' },
    { code: 'AL', name: 'Alagoas' },
    { code: 'AP', name: 'Amapá' },
    { code: 'AM', name: 'Amazonas' },
    { code: 'BA', name: 'Bahia' },
    { code: 'CE', name: 'Ceará' },
    { code: 'DF', name: 'District fédéral' },
    { code: 'ES', name: 'Espírito Santo' },
    { code: 'GO', name: 'Goiás' },
    { code: 'MA', name: 'Maranhão' },
    { code: 'MT', name: 'Mato Grosso' },
    { code: 'MS', name: 'Mato Grosso do Sul' },
    { code: 'MG', name: 'Minas Gerais' },
    { code: 'PA', name: 'Pará' },
    { code: 'PB', name: 'Paraíba' },
    { code: 'PR', name: 'Paraná' },
    { code: 'PE', name: 'Pernambouc' },
    { code: 'PI', name: 'Piauí' },
    { code: 'RJ', name: 'Rio de Janeiro' },
    { code: 'RN', name: 'Rio Grande do Norte' },
    { code: 'RS', name: 'Rio Grande do Sul' },
    { code: 'RO', name: 'Rondônia' },
    { code: 'RR', name: 'Roraima' },
    { code: 'SC', name: 'Santa Catarina' },
    { code: 'SP', name: 'São Paulo' },
    { code: 'SE', name: 'Sergipe' },
    { code: 'TO', name: 'Tocantins' },
  ],
  GB: [
    { code: 'ENG', name: 'Angleterre' },
    { code: 'SCT', name: 'Écosse' },
    { code: 'WLS', name: 'Pays de Galles' },
    { code: 'NIR', name: 'Irlande du Nord' },
  ],
  DE: [
    { code: 'BW', name: 'Bade-Wurtemberg' },
    { code: 'BY', name: 'Bavière' },
    { code: 'BE', name: 'Berlin' },
    { code: 'BB', name: 'Brandebourg' },
    { code: 'HB', name: 'Brême' },
    { code: 'HH', name: 'Hambourg' },
    { code: 'HE', name: 'Hesse' },
    { code: 'MV', name: 'Mecklembourg-Poméranie-Occidentale' },
    { code: 'NI', name: 'Basse-Saxe' },
    { code: 'NW', name: 'Rhénanie-du-Nord-Westphalie' },
    { code: 'RP', name: 'Rhénanie-Palatinat' },
    { code: 'SL', name: 'Sarre' },
    { code: 'SN', name: 'Saxe' },
    { code: 'ST', name: 'Saxe-Anhalt' },
    { code: 'SH', name: 'Schleswig-Holstein' },
    { code: 'TH', name: 'Thuringe' },
  ],
  ES: [
    { code: 'AN', name: 'Andalousie' },
    { code: 'AR', name: 'Aragon' },
    { code: 'AS', name: 'Asturies' },
    { code: 'IB', name: 'Îles Baléares' },
    { code: 'PV', name: 'Pays basque' },
    { code: 'CN', name: 'Îles Canaries' },
    { code: 'CB', name: 'Cantabrie' },
    { code: 'CL', name: 'Castille-et-León' },
    { code: 'CM', name: 'Castille-La Manche' },
    { code: 'CT', name: 'Catalogne' },
    { code: 'EX', name: 'Estrémadure' },
    { code: 'GA', name: 'Galice' },
    { code: 'RI', name: 'La Rioja' },
    { code: 'MD', name: 'Madrid' },
    { code: 'MC', name: 'Murcie' },
    { code: 'NC', name: 'Navarre' },
    { code: 'VC', name: 'Communauté valencienne' },
  ],
  IT: [
    { code: 'ABR', name: 'Abruzzes' },
    { code: 'BAS', name: 'Basilicate' },
    { code: 'CAL', name: 'Calabre' },
    { code: 'CAM', name: 'Campanie' },
    { code: 'EMR', name: 'Émilie-Romagne' },
    { code: 'FVG', name: 'Frioul-Vénétie julienne' },
    { code: 'LAZ', name: 'Latium' },
    { code: 'LIG', name: 'Ligurie' },
    { code: 'LOM', name: 'Lombardie' },
    { code: 'MAR', name: 'Marches' },
    { code: 'MOL', name: 'Molise' },
    { code: 'PMN', name: 'Piémont' },
    { code: 'PUG', name: 'Pouilles' },
    { code: 'SAR', name: 'Sardaigne' },
    { code: 'SIC', name: 'Sicile' },
    { code: 'TOS', name: 'Toscane' },
    { code: 'TAA', name: 'Trentin-Haut-Adige' },
    { code: 'UMB', name: 'Ombrie' },
    { code: 'VDA', name: 'Vallée d\'Aoste' },
    { code: 'VEN', name: 'Vénétie' },
  ],
  IN: [
    { code: 'AN', name: 'Îles Andaman-et-Nicobar' },
    { code: 'AP', name: 'Andhra Pradesh' },
    { code: 'AR', name: 'Arunachal Pradesh' },
    { code: 'AS', name: 'Assam' },
    { code: 'BR', name: 'Bihar' },
    { code: 'CH', name: 'Chandigarh' },
    { code: 'CT', name: 'Chhattisgarh' },
    { code: 'DL', name: 'Delhi' },
    { code: 'GA', name: 'Goa' },
    { code: 'GJ', name: 'Gujarat' },
    { code: 'HR', name: 'Haryana' },
    { code: 'HP', name: 'Himachal Pradesh' },
    { code: 'JK', name: 'Jammu-et-Cachemire' },
    { code: 'JH', name: 'Jharkhand' },
    { code: 'KA', name: 'Karnataka' },
    { code: 'KL', name: 'Kerala' },
    { code: 'MP', name: 'Madhya Pradesh' },
    { code: 'MH', name: 'Maharashtra' },
    { code: 'MN', name: 'Manipur' },
    { code: 'ML', name: 'Meghalaya' },
    { code: 'MZ', name: 'Mizoram' },
    { code: 'NL', name: 'Nagaland' },
    { code: 'OR', name: 'Odisha' },
    { code: 'PB', name: 'Pendjab' },
    { code: 'RJ', name: 'Rajasthan' },
    { code: 'SK', name: 'Sikkim' },
    { code: 'TN', name: 'Tamil Nadu' },
    { code: 'TG', name: 'Télangana' },
    { code: 'TR', name: 'Tripura' },
    { code: 'UP', name: 'Uttar Pradesh' },
    { code: 'UT', name: 'Uttarakhand' },
    { code: 'WB', name: 'Bengale-Occidental' },
  ],
  AR: [
    { code: 'BA', name: 'Buenos Aires' },
    { code: 'CT', name: 'Ville autonome de Buenos Aires' },
    { code: 'CB', name: 'Catamarca' },
    { code: 'CH', name: 'Chaco' },
    { code: 'CU', name: 'Chubut' },
    { code: 'CC', name: 'Córdoba' },
    { code: 'CN', name: 'Corrientes' },
    { code: 'ER', name: 'Entre Ríos' },
    { code: 'FM', name: 'Formosa' },
    { code: 'JY', name: 'Jujuy' },
    { code: 'LP', name: 'La Pampa' },
    { code: 'LR', name: 'La Rioja' },
    { code: 'MZ', name: 'Mendoza' },
    { code: 'MN', name: 'Misiones' },
    { code: 'NQ', name: 'Neuquén' },
    { code: 'RN', name: 'Río Negro' },
    { code: 'SA', name: 'Salta' },
    { code: 'SJ', name: 'San Juan' },
    { code: 'SL', name: 'San Luis' },
    { code: 'SC', name: 'Santa Cruz' },
    { code: 'SF', name: 'Santa Fe' },
    { code: 'SE', name: 'Santiago del Estero' },
    { code: 'TF', name: 'Terre de Feu' },
    { code: 'TM', name: 'Tucumán' },
  ],
  CN: [
    { code: 'BJ', name: 'Pékin' },
    { code: 'SH', name: 'Shanghai' },
    { code: 'GD', name: 'Guangdong' },
    { code: 'ZJ', name: 'Zhejiang' },
    { code: 'JS', name: 'Jiangsu' },
    { code: 'SD', name: 'Shandong' },
    { code: 'HN', name: 'Henan' },
    { code: 'SC', name: 'Sichuan' },
    { code: 'HB', name: 'Hubei' },
    { code: 'HN2', name: 'Hunan' },
    { code: 'FJ', name: 'Fujian' },
    { code: 'AH', name: 'Anhui' },
    { code: 'LN', name: 'Liaoning' },
    { code: 'SX', name: 'Shanxi' },
    { code: 'JX', name: 'Jiangxi' },
    { code: 'GX', name: 'Guangxi' },
    { code: 'YN', name: 'Yunnan' },
    { code: 'GZ', name: 'Guizhou' },
    { code: 'SN', name: 'Shaanxi' },
    { code: 'HL', name: 'Heilongjiang' },
    { code: 'TJ', name: 'Tianjin' },
    { code: 'CQ', name: 'Chongqing' },
  ],
  JP: [
    { code: '13', name: 'Tokyo' },
    { code: '27', name: 'Osaka' },
    { code: '14', name: 'Kanagawa' },
    { code: '23', name: 'Aichi' },
    { code: '11', name: 'Saitama' },
    { code: '12', name: 'Chiba' },
    { code: '28', name: 'Hyōgo' },
    { code: '40', name: 'Fukuoka' },
    { code: '01', name: 'Hokkaidō' },
    { code: '26', name: 'Kyoto' },
  ],
  ID: [
    { code: 'JK', name: 'Jakarta' },
    { code: 'JB', name: 'Java Ouest' },
    { code: 'JT', name: 'Java Central' },
    { code: 'JI', name: 'Java Est' },
    { code: 'BA', name: 'Bali' },
    { code: 'SU', name: 'Sumatra Nord' },
    { code: 'SA', name: 'Sulawesi Nord' },
    { code: 'KI', name: 'Kalimantan Est' },
  ],
  PH: [
    { code: 'NCR', name: 'Grand Manille' },
    { code: 'CAL', name: 'Calabarzon' },
    { code: 'CLU', name: 'Luçon centrale' },
    { code: 'VIS', name: 'Visayas' },
    { code: 'MIN', name: 'Mindanao' },
  ],
  AE: [
    { code: 'AZ', name: 'Abou Dabi' },
    { code: 'DU', name: 'Dubaï' },
    { code: 'SH', name: 'Charjah' },
    { code: 'AJ', name: 'Ajman' },
    { code: 'UQ', name: 'Umm al-Qaïwain' },
    { code: 'RK', name: 'Ras el Khaïmah' },
    { code: 'FU', name: 'Fujaïrah' },
  ],
  NG: [
    { code: 'LA', name: 'Lagos' },
    { code: 'FC', name: 'Territoire de la capitale fédérale' },
    { code: 'KN', name: 'Kano' },
    { code: 'RV', name: 'Rivers' },
    { code: 'OY', name: 'Oyo' },
    { code: 'KD', name: 'Kaduna' },
    { code: 'EN', name: 'Enugu' },
    { code: 'DE', name: 'Delta' },
  ],
  ZA: [
    { code: 'GP', name: 'Gauteng' },
    { code: 'WC', name: 'Cap-Occidental' },
    { code: 'KZN', name: 'KwaZulu-Natal' },
    { code: 'EC', name: 'Cap-Oriental' },
    { code: 'MP', name: 'Mpumalanga' },
    { code: 'LP', name: 'Limpopo' },
    { code: 'NW', name: 'Nord-Ouest' },
    { code: 'FS', name: 'État libre' },
    { code: 'NC', name: 'Cap-Nord' },
  ],
  KR: [
    { code: '11', name: 'Séoul' },
    { code: '26', name: 'Busan' },
    { code: '27', name: 'Daegu' },
    { code: '28', name: 'Incheon' },
    { code: '41', name: 'Gyeonggi' },
    { code: '42', name: 'Gangwon' },
  ],
  TR: [
    { code: '34', name: 'Istanbul' },
    { code: '06', name: 'Ankara' },
    { code: '35', name: 'Izmir' },
    { code: '07', name: 'Antalya' },
    { code: '16', name: 'Bursa' },
    { code: '42', name: 'Konya' },
  ],
  PL: [
    { code: 'MZ', name: 'Mazovie' },
    { code: 'SL', name: 'Silésie' },
    { code: 'WP', name: 'Grande-Pologne' },
    { code: 'MA', name: 'Petite-Pologne' },
    { code: 'DS', name: 'Basse-Silésie' },
    { code: 'PM', name: 'Poméranie' },
    { code: 'LD', name: 'Łódź' },
  ],
  NL: [
    { code: 'NH', name: 'Hollande-Septentrionale' },
    { code: 'ZH', name: 'Hollande-Méridionale' },
    { code: 'UT', name: 'Utrecht' },
    { code: 'NB', name: 'Brabant-Septentrional' },
    { code: 'GE', name: 'Gueldre' },
    { code: 'OV', name: 'Overijssel' },
    { code: 'LI', name: 'Limbourg' },
    { code: 'FR', name: 'Frise' },
    { code: 'GR', name: 'Groningue' },
    { code: 'DR', name: 'Drenthe' },
    { code: 'FL', name: 'Flevoland' },
    { code: 'ZE', name: 'Zélande' },
  ],
  AT: [
    { code: '9', name: 'Vienne' },
    { code: '4', name: 'Haute-Autriche' },
    { code: '6', name: 'Styrie' },
    { code: '7', name: 'Tyrol' },
    { code: '5', name: 'Salzbourg' },
    { code: '8', name: 'Vorarlberg' },
    { code: '3', name: 'Basse-Autriche' },
    { code: '2', name: 'Carinthie' },
    { code: '1', name: 'Burgenland' },
  ],
  NZ: [
    { code: 'AUK', name: 'Auckland' },
    { code: 'WGN', name: 'Wellington' },
    { code: 'CAN', name: 'Canterbury' },
    { code: 'WKO', name: 'Waikato' },
    { code: 'OTA', name: 'Otago' },
    { code: 'BOP', name: 'Baie de l\'Abondance' },
  ],
  MY: [
    { code: '14', name: 'Kuala Lumpur' },
    { code: '10', name: 'Selangor' },
    { code: '07', name: 'Penang' },
    { code: '01', name: 'Johor' },
    { code: '12', name: 'Sabah' },
    { code: '13', name: 'Sarawak' },
    { code: '11', name: 'Terengganu' },
    { code: '03', name: 'Kelantan' },
  ],
  TH: [
    { code: '10', name: 'Bangkok' },
    { code: '50', name: 'Chiang Mai' },
    { code: '20', name: 'Chonburi' },
    { code: '83', name: 'Phuket' },
    { code: '90', name: 'Songkhla' },
  ],
  EG: [
    { code: 'C', name: 'Le Caire' },
    { code: 'ALX', name: 'Alexandrie' },
    { code: 'GZ', name: 'Gizeh' },
    { code: 'SHR', name: 'Ach-Charqiya' },
    { code: 'DK', name: 'Dakahlia' },
  ],
  SA: [
    { code: '01', name: 'Riyad' },
    { code: '02', name: 'La Mecque' },
    { code: '03', name: 'Médine' },
    { code: '04', name: 'Ach-Charqiya' },
    { code: '05', name: 'Al-Qassim' },
    { code: '06', name: 'Haïl' },
    { code: '07', name: 'Tabuk' },
  ],
  CO: [
    { code: 'DC', name: 'Bogotá' },
    { code: 'ANT', name: 'Antioquia' },
    { code: 'VAC', name: 'Valle del Cauca' },
    { code: 'ATL', name: 'Atlántico' },
    { code: 'SAN', name: 'Santander' },
    { code: 'BOL', name: 'Bolívar' },
    { code: 'CUN', name: 'Cundinamarca' },
  ],
  CL: [
    { code: 'RM', name: 'Région métropolitaine de Santiago' },
    { code: 'VS', name: 'Valparaíso' },
    { code: 'BI', name: 'Biobío' },
    { code: 'ML', name: 'Maule' },
    { code: 'AR', name: 'Araucanie' },
    { code: 'AN', name: 'Antofagasta' },
  ],
  PE: [
    { code: 'LIM', name: 'Lima' },
    { code: 'ARE', name: 'Arequipa' },
    { code: 'CUS', name: 'Cusco' },
    { code: 'LAL', name: 'La Libertad' },
    { code: 'PIU', name: 'Piura' },
    { code: 'JUN', name: 'Junín' },
  ],
  VE: [
    { code: 'A', name: 'Distrito Capital' },
    { code: 'B', name: 'Anzoátegui' },
    { code: 'G', name: 'Carabobo' },
    { code: 'K', name: 'Lara' },
    { code: 'M', name: 'Miranda' },
    { code: 'V', name: 'Zulia' },
  ],
  PT: [
    { code: '11', name: 'Lisbonne' },
    { code: '13', name: 'Porto' },
    { code: '15', name: 'Setúbal' },
    { code: '03', name: 'Braga' },
    { code: '08', name: 'Faro' },
  ],
  IE: [
    { code: 'L', name: 'Leinster' },
    { code: 'M', name: 'Munster' },
    { code: 'C', name: 'Connacht' },
    { code: 'U', name: 'Ulster' },
  ],
  SE: [
    { code: 'AB', name: 'Comté de Stockholm' },
    { code: 'M', name: 'Comté de Scanie' },
    { code: 'O', name: 'Comté de Västra Götaland' },
    { code: 'C', name: 'Comté d\'Uppsala' },
  ],
  NO: [
    { code: '03', name: 'Oslo' },
    { code: '11', name: 'Rogaland' },
    { code: '15', name: 'Møre og Romsdal' },
    { code: '18', name: 'Nordland' },
    { code: '50', name: 'Trøndelag' },
  ],
  DK: [
    { code: '84', name: 'Hovedstaden' },
    { code: '82', name: 'Jutland central' },
    { code: '83', name: 'Danemark du Sud' },
    { code: '81', name: 'Jutland du Nord' },
    { code: '85', name: 'Zélande' },
  ],
  FI: [
    { code: '18', name: 'Uusimaa' },
    { code: '19', name: 'Finlande du Sud-Ouest' },
    { code: '06', name: 'Pirkanmaa' },
    { code: '14', name: 'Ostrobotnie du Nord' },
  ],
  RU: [
    { code: 'MOW', name: 'Moscou' },
    { code: 'SPE', name: 'Saint-Pétersbourg' },
    { code: 'MOS', name: 'Oblast de Moscou' },
    { code: 'KDA', name: 'Krasnodar' },
    { code: 'SVE', name: 'Sverdlovsk' },
    { code: 'ROS', name: 'Rostov' },
    { code: 'TA', name: 'Tatarstan' },
  ],
  UA: [
    { code: '30', name: 'Kiev' },
    { code: '63', name: 'Kharkiv' },
    { code: '48', name: 'Dnipropetrovsk' },
    { code: '51', name: 'Odessa' },
    { code: '46', name: 'Lviv' },
  ],
  PK: [
    { code: 'PB', name: 'Pendjab' },
    { code: 'SD', name: 'Sindh' },
    { code: 'KP', name: 'Khyber Pakhtunkhwa' },
    { code: 'BA', name: 'Baloutchistan' },
    { code: 'IS', name: 'Islamabad' },
  ],
  BD: [
    { code: 'C', name: 'Dhaka' },
    { code: 'B', name: 'Chittagong' },
    { code: 'A', name: 'Barisal' },
    { code: 'D', name: 'Khulna' },
    { code: 'E', name: 'Rajshahi' },
  ],
  VN: [
    { code: 'HN', name: 'Hanoï' },
    { code: 'SG', name: 'Hô Chi Minh-Ville' },
    { code: 'DN', name: 'Đà Nẵng' },
    { code: 'HP', name: 'Hải Phòng' },
    { code: 'CT', name: 'Cần Thơ' },
  ],
  MA: [
    { code: 'CAS', name: 'Casablanca-Settat' },
    { code: 'RAB', name: 'Rabat-Salé-Kénitra' },
    { code: 'MAR', name: 'Marrakech-Safi' },
    { code: 'FES', name: 'Fès-Meknès' },
    { code: 'TNG', name: 'Tanger-Tétouan-Al Hoceïma' },
  ],
  DZ: [
    { code: '16', name: 'Alger' },
    { code: '31', name: 'Oran' },
    { code: '25', name: 'Constantine' },
    { code: '09', name: 'Blida' },
    { code: '19', name: 'Sétif' },
  ],
  IL: [
    { code: 'TA', name: 'Tel Aviv' },
    { code: 'JM', name: 'Jérusalem' },
    { code: 'HA', name: 'Haïfa' },
    { code: 'Z', name: 'District centre' },
    { code: 'D', name: 'District sud' },
  ],
  GR: [
    { code: 'I', name: 'Attique' },
    { code: 'B', name: 'Macédoine-Centrale' },
    { code: 'M', name: 'Crète' },
    { code: 'G', name: 'Thessalie' },
    { code: 'H', name: 'Épire' },
  ],
  CZ: [
    { code: '10', name: 'Prague' },
    { code: '64', name: 'Moravie du Sud' },
    { code: '42', name: 'Région d\'Ústí nad Labem' },
    { code: '52', name: 'Pardubice' },
    { code: '63', name: 'Vysočina' },
  ],
  RO: [
    { code: 'B', name: 'Bucarest' },
    { code: 'CJ', name: 'Cluj' },
    { code: 'TM', name: 'Timișoara' },
    { code: 'IS', name: 'Iași' },
    { code: 'CT', name: 'Constanța' },
  ],
  HU: [
    { code: 'BU', name: 'Budapest' },
    { code: 'PE', name: 'Pest' },
    { code: 'GY', name: 'Győr-Moson-Sopron' },
    { code: 'BA', name: 'Baranya' },
    { code: 'CS', name: 'Csongrád-Csanád' },
  ],
};
