import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outFile = path.join(__dirname, '..', 'constants', 'regionData', 'countries.generated.ts');

/** ISO 3166-1 alpha-2 countries and common territories with French display names. */
const ISO_COUNTRIES = [
  ['AF', 'Afghanistan'],
  ['ZA', 'Afrique du Sud'],
  ['AL', 'Albanie'],
  ['DZ', 'Algérie'],
  ['DE', 'Allemagne'],
  ['AD', 'Andorre'],
  ['AO', 'Angola'],
  ['AG', 'Antigua-et-Barbuda'],
  ['SA', 'Arabie saoudite'],
  ['AR', 'Argentine'],
  ['AM', 'Arménie'],
  ['AU', 'Australie'],
  ['AT', 'Autriche'],
  ['AZ', 'Azerbaïdjan'],
  ['BS', 'Bahamas'],
  ['BH', 'Bahreïn'],
  ['BD', 'Bangladesh'],
  ['BB', 'Barbade'],
  ['BE', 'Belgique'],
  ['BZ', 'Belize'],
  ['BJ', 'Bénin'],
  ['BT', 'Bhoutan'],
  ['BY', 'Biélorussie'],
  ['BO', 'Bolivie'],
  ['BA', 'Bosnie-Herzégovine'],
  ['BW', 'Botswana'],
  ['BR', 'Brésil'],
  ['BN', 'Brunei'],
  ['BG', 'Bulgarie'],
  ['BF', 'Burkina Faso'],
  ['BI', 'Burundi'],
  ['KH', 'Cambodge'],
  ['CM', 'Cameroun'],
  ['CA', 'Canada'],
  ['CV', 'Cap-Vert'],
  ['CL', 'Chili'],
  ['CN', 'Chine'],
  ['CY', 'Chypre'],
  ['CO', 'Colombie'],
  ['KM', 'Comores'],
  ['CG', 'Congo'],
  ['CD', 'Congo (RDC)'],
  ['KP', 'Corée du Nord'],
  ['KR', 'Corée du Sud'],
  ['CR', 'Costa Rica'],
  ['CI', "Côte d'Ivoire"],
  ['HR', 'Croatie'],
  ['CU', 'Cuba'],
  ['DK', 'Danemark'],
  ['DJ', 'Djibouti'],
  ['DM', 'Dominique'],
  ['EG', 'Égypte'],
  ['AE', 'Émirats arabes unis'],
  ['EC', 'Équateur'],
  ['ER', 'Érythrée'],
  ['ES', 'Espagne'],
  ['EE', 'Estonie'],
  ['SZ', 'Eswatini'],
  ['US', 'États-Unis'],
  ['ET', 'Éthiopie'],
  ['FJ', 'Fidji'],
  ['FI', 'Finlande'],
  ['FR', 'France'],
  ['GA', 'Gabon'],
  ['GM', 'Gambie'],
  ['GE', 'Géorgie'],
  ['GH', 'Ghana'],
  ['GR', 'Grèce'],
  ['GD', 'Grenade'],
  ['GT', 'Guatemala'],
  ['GN', 'Guinée'],
  ['GW', 'Guinée-Bissau'],
  ['GQ', 'Guinée équatoriale'],
  ['GY', 'Guyana'],
  ['HT', 'Haïti'],
  ['HN', 'Honduras'],
  ['HU', 'Hongrie'],
  ['IN', 'Inde'],
  ['ID', 'Indonésie'],
  ['IQ', 'Irak'],
  ['IR', 'Iran'],
  ['IE', 'Irlande'],
  ['IS', 'Islande'],
  ['IL', 'Israël'],
  ['IT', 'Italie'],
  ['JM', 'Jamaïque'],
  ['JP', 'Japon'],
  ['JO', 'Jordanie'],
  ['KZ', 'Kazakhstan'],
  ['KE', 'Kenya'],
  ['KG', 'Kirghizistan'],
  ['KI', 'Kiribati'],
  ['KW', 'Koweït'],
  ['LA', 'Laos'],
  ['LS', 'Lesotho'],
  ['LV', 'Lettonie'],
  ['LB', 'Liban'],
  ['LR', 'Liberia'],
  ['LY', 'Libye'],
  ['LI', 'Liechtenstein'],
  ['LT', 'Lituanie'],
  ['LU', 'Luxembourg'],
  ['MK', 'Macédoine du Nord'],
  ['MG', 'Madagascar'],
  ['MY', 'Malaisie'],
  ['MW', 'Malawi'],
  ['MV', 'Maldives'],
  ['ML', 'Mali'],
  ['MT', 'Malte'],
  ['MA', 'Maroc'],
  ['MH', 'Îles Marshall'],
  ['MU', 'Maurice'],
  ['MR', 'Mauritanie'],
  ['MX', 'Mexique'],
  ['FM', 'Micronésie'],
  ['MD', 'Moldavie'],
  ['MC', 'Monaco'],
  ['MN', 'Mongolie'],
  ['ME', 'Monténégro'],
  ['MZ', 'Mozambique'],
  ['MM', 'Myanmar'],
  ['NA', 'Namibie'],
  ['NR', 'Nauru'],
  ['NP', 'Népal'],
  ['NI', 'Nicaragua'],
  ['NE', 'Niger'],
  ['NG', 'Nigeria'],
  ['NO', 'Norvège'],
  ['NZ', 'Nouvelle-Zélande'],
  ['OM', 'Oman'],
  ['UG', 'Ouganda'],
  ['UZ', 'Ouzbékistan'],
  ['PK', 'Pakistan'],
  ['PW', 'Palaos'],
  ['PA', 'Panama'],
  ['PG', 'Papouasie-Nouvelle-Guinée'],
  ['PY', 'Paraguay'],
  ['NL', 'Pays-Bas'],
  ['PE', 'Pérou'],
  ['PH', 'Philippines'],
  ['PL', 'Pologne'],
  ['PT', 'Portugal'],
  ['QA', 'Qatar'],
  ['CF', 'République centrafricaine'],
  ['DO', 'République dominicaine'],
  ['CZ', 'République tchèque'],
  ['RO', 'Roumanie'],
  ['GB', 'Royaume-Uni'],
  ['RW', 'Rwanda'],
  ['KN', 'Saint-Kitts-et-Nevis'],
  ['SM', 'Saint-Marin'],
  ['LC', 'Sainte-Lucie'],
  ['VC', 'Saint-Vincent-et-les-Grenadines'],
  ['SB', 'Îles Salomon'],
  ['SV', 'Salvador'],
  ['WS', 'Samoa'],
  ['ST', 'São Tomé-et-Príncipe'],
  ['SN', 'Sénégal'],
  ['RS', 'Serbie'],
  ['SC', 'Seychelles'],
  ['SL', 'Sierra Leone'],
  ['SG', 'Singapour'],
  ['SK', 'Slovaquie'],
  ['SI', 'Slovénie'],
  ['SO', 'Somalie'],
  ['SD', 'Soudan'],
  ['SS', 'Soudan du Sud'],
  ['LK', 'Sri Lanka'],
  ['SE', 'Suède'],
  ['CH', 'Suisse'],
  ['SR', 'Suriname'],
  ['SY', 'Syrie'],
  ['TJ', 'Tadjikistan'],
  ['TW', 'Taïwan'],
  ['TZ', 'Tanzanie'],
  ['TD', 'Tchad'],
  ['TH', 'Thaïlande'],
  ['TL', 'Timor oriental'],
  ['TG', 'Togo'],
  ['TO', 'Tonga'],
  ['TT', 'Trinité-et-Tobago'],
  ['TN', 'Tunisie'],
  ['TM', 'Turkménistan'],
  ['TR', 'Turquie'],
  ['TV', 'Tuvalu'],
  ['UA', 'Ukraine'],
  ['UY', 'Uruguay'],
  ['VU', 'Vanuatu'],
  ['VA', 'Vatican'],
  ['VE', 'Venezuela'],
  ['VN', 'Viêt Nam'],
  ['YE', 'Yémen'],
  ['ZM', 'Zambie'],
  ['ZW', 'Zimbabwe'],
  // Territories and special areas commonly used in locale detection
  ['HK', 'Hong Kong'],
  ['MO', 'Macao'],
  ['PR', 'Porto Rico'],
  ['GU', 'Guam'],
  ['VI', 'Îles Vierges américaines'],
  ['AS', 'Samoa américaines'],
  ['MP', 'Îles Mariannes du Nord'],
  ['GF', 'Guyane française'],
  ['PF', 'Polynésie française'],
  ['NC', 'Nouvelle-Calédonie'],
  ['RE', 'La Réunion'],
  ['MQ', 'Martinique'],
  ['GP', 'Guadeloupe'],
  ['YT', 'Mayotte'],
  ['BL', 'Saint-Barthélemy'],
  ['MF', 'Saint-Martin'],
  ['PM', 'Saint-Pierre-et-Miquelon'],
  ['WF', 'Wallis-et-Futuna'],
  ['FO', 'Îles Féroé'],
  ['GI', 'Gibraltar'],
  ['GG', 'Guernesey'],
  ['JE', 'Jersey'],
  ['IM', 'Île de Man'],
  ['AX', 'Åland'],
  ['GL', 'Groenland'],
  ['BM', 'Bermudes'],
  ['KY', 'Îles Caïmans'],
  ['TC', 'Îles Turques-et-Caïques'],
  ['VG', 'Îles Vierges britanniques'],
  ['FK', 'Îles Malouines'],
  ['AW', 'Aruba'],
  ['CW', 'Curaçao'],
  ['SX', 'Saint-Martin (Pays-Bas)'],
  ['BQ', 'Pays-Bas caribéens'],
  ['XK', 'Kosovo'],
  ['PS', 'Palestine'],
  ['EH', 'Sahara occidental'],
];

const lines = [
  '/** Auto-generated by scripts/generate-regions.mjs — do not edit manually. */',
  "import type { CountryEntry } from '@/constants/regionData/types';",
  '',
  'export const ISO_COUNTRY_ENTRIES: Omit<CountryEntry, "regions">[] = [',
  ...ISO_COUNTRIES.map(([code, name]) => `  { countryCode: '${code}', countryName: '${name.replace(/'/g, "\\'")}' },`),
  '];',
  '',
  `export const ISO_COUNTRY_COUNT = ${ISO_COUNTRIES.length};`,
  '',
];

fs.writeFileSync(outFile, lines.join('\n'), 'utf8');
console.log(`Wrote ${ISO_COUNTRIES.length} countries to ${outFile}`);
